// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsgubzyzausmguhzvgju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzZ3Vienl6YXVzbWd1aHp2Z2p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMTYwNTcsImV4cCI6MjA3MTY5MjA1N30.xVFomSzJhb8gJq2aYYDhyLlIrRtqdas4NkJfOn-QzXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});